on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: ['17.0.12', 21, 23, 25]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: ${{ matrix.version }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: |
          ./gradlew build
          ./gradlew nativeCompile
      - name: Test
        run: |
          echo "####### Normal Run #######"
          ./gradlew app:run
          echo "####### Native Image Run #######"
          ./app/build/native/nativeCompile/test || true
